// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpxLQGXHh19lOxkc4j3HCJcJTmjpKRwls',
    appId: '1:227386321747:web:6774c9d8570ba900904fa6',
    messagingSenderId: '227386321747',
    projectId: 'ecoloop-app-ef8de',
    authDomain: 'ecoloop-app-ef8de.firebaseapp.com',
    storageBucket: 'ecoloop-app-ef8de.firebasestorage.app',
    measurementId: 'G-H6VDZVT34H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbIcLHc7yqXxDjTw_Gw3FHCEmcao5JrLo',
    appId: '1:227386321747:android:9a7beb4c8195f78f904fa6',
    messagingSenderId: '227386321747',
    projectId: 'ecoloop-app-ef8de',
    storageBucket: 'ecoloop-app-ef8de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5kB2rZQB_cKP-yENcTpzLkbqhdWGk320',
    appId: '1:227386321747:ios:71aab6ea54940bf4904fa6',
    messagingSenderId: '227386321747',
    projectId: 'ecoloop-app-ef8de',
    storageBucket: 'ecoloop-app-ef8de.firebasestorage.app',
    iosBundleId: 'com.example.ecoLoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5kB2rZQB_cKP-yENcTpzLkbqhdWGk320',
    appId: '1:227386321747:ios:71aab6ea54940bf4904fa6',
    messagingSenderId: '227386321747',
    projectId: 'ecoloop-app-ef8de',
    storageBucket: 'ecoloop-app-ef8de.firebasestorage.app',
    iosBundleId: 'com.example.ecoLoop',
  );
}
